apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: enuygun-case
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - "while true; do wget -q -O- http://sample-app.enuygun-case.svc.cluster.local; done" 